version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: recipesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe -d recipesdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  recipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-app
    environment:
      DATABASE_URL: postgres://recipe:12345@postgres:5432/recipesdb
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
